namespace: dev

movieService:
  image: nessrine80/movie_service:latest
  databaseUri: postgresql://movie_db_username:movie_db_password@movie-db/movie_db_dev
  castUrl: http://cast-service:8000/api/v1/casts/

castService:
  image: nessrine80/cast_service:latest
  databaseUri: postgresql://cast_db_username:cast_db_password@cast-db/cast_db_dev

nginx:
  image: nginx:latest
  port: 8080

